#!/usr/bin/env bash

set -Eeo pipefail
set +m
shopt -s lastpipe

TEMPFILE=
FILENAME="screenshot_$(date +%Y-%m-%d_%H:%M:%S).png"
DIRECTORY="$HOME/Pictures/Screenshots"
MODES=()
CLIPBOARD=y
ANNOTATE=false
FREEZE=false
FREEZE_PID=
REGION=false
RECTANGLES=
PREDEFINED=

usage() {
	printf %s "Usage: $0 [opts]
	-h                   Print this message
	-m <mode>            The mode to use for screenshot area selection, multiple can be used (region, window, output, layer)
	-f <filename>        Name of the outputted file
	-d <directory>       Path to the directory screenshots are stored in (created if it doesn't exist)
	-o                   Save the screenshot only onto clipboard (incompatible with -n)
	-n                   Don't copy screenshot to clipboard (incompatible with -o)
	-c <mode>            Specify clipboard mode (yes, no, only)
	-a <satty/swappy>    Open screenshot in annotation app, satty is used if neither is specified
	-z                   Freeze display during screenshot
	-p                   Screenshot a predefined area immediately. Disabled freeze
"
}

fail() {
	printf %s\\n "$2"
	usage
	exit "$1"
}

apply_transform() {
	local t x y w h w2 h2
	while read -r t x y w h; do
		case "$t" in
		0 | 2)
			w2="$w"
			h2="$h"
			;;
		1 | 3)
			w2="$h"
			h2="$w"
			;;
		*)
			fail 6 "Invalid transform: $t"
			;;
		esac
		printf %s\\n "$x,$y ${w2}x${h2}"
	done
}

handle_notification_action() {
	if [[ $1 == "default" ]]; then
		xdg-open "$DIRECTORY" &
		disown
	fi
}

notify() {
	case "${CLIPBOARD[0]}" in
	n)
		handle_notification_action "$(notify-send -u low -a Katshot -A 'default=Open Directory' 'Screenshot saved' "$DIRECTORY/$FILENAME")"
		;;
	o)
		handle_notification_action "$(notify-send -u low -a Katshot 'Screenshot copied')"
		;;
	*)
		handle_notification_action "$(notify-send -u low -a Katshot -A 'default=Open Directory' 'Screenshot saved & copied' "$DIRECTORY/$FILENAME")"
		;;
	esac
}

cleanup() {
	# sleep 0.1
	rm -f "$TEMPFILE" "$TEMPFILE.png"
	kill "$FREEZE_PID" 1>/dev/null 2>&1
}
trap cleanup 0

save_screenshot() {
	mkdir "$DIRECTORY" -p
	if [[ $(stat "$TEMPFILE.png" 2>/dev/null) ]]; then
		cp "$TEMPFILE.png" "$DIRECTORY/$FILENAME"
	else
		cp "$TEMPFILE" "$DIRECTORY/$FILENAME"
	fi
}

clipboard_screenshot() {
	if [[ $(stat "$TEMPFILE.png" 2>/dev/null) ]]; then
		wl-copy -t image/png <"$TEMPFILE.png"
	else
		wl-copy -t image/png <"$TEMPFILE"
	fi
}

grab_init() {
	TEMPFILE="$(mktemp)"
	if $FREEZE; then
		if [[ $(command -v wayfreeze) ]]; then
			wayfreeze &
			sleep 0.2
			FREEZE_PID=$!
		elif [[ $(command -v hyprpicker) ]]; then
			hyprpicker -r -z >/dev/null &
			sleep 0.1
			FREEZE_PID=$!
		else
			printf %s\\n "Wayfreeze or hyprpicker not found, can't freeze"
		fi
	fi
}

get_rectangles() {
	local rects=
	((${#MODES[@]} > 0)) || MODES+=("region")
	for MODE in "${MODES[@]}"; do
		case "$MODE" in
		region)
			REGION=true
			;;
		window)
			rects+="$(get_windows)"$'\n'
			;;
		output)
			rects+="$(get_outputs)"$'\n'
			;;
		layer)
			rects+="$(get_layers)"$'\n'
			;;
		esac
	done
	printf -v RECTANGLES %s "$rects"
}

get_windows() {
	local workspaces
	workspaces="$(hyprctl monitors -j | jq 'map(if .specialWorkspace.id != 0 then .specialWorkspace.id else .activeWorkspace.id end) | join(",")' -r)"
	hyprctl clients -j | jq '.[] | select(.workspace.id | contains('"$workspaces"')) | [(.at | join(",")), " ", (.size | join("x"))] | add' -r
}

get_layers() {
	hyprctl layers -j | jq 'map(.levels).[] | add | .[] | "\(.x),\(.y) \(.w)x\(.h)"' -r
}

get_outputs() {
	hyprctl monitors -j | jq '.[] | "\(.transform) \(.x) \(.y) \(.width) \(.height)"' -r | apply_transform
}

capture() {
	local args geometry
	if $REGION; then args=; else args=-r; fi
	if [[ -n $PREDEFINED ]]; then
		geometry="$PREDEFINED"
	else
		geometry="$(printf %s "$RECTANGLES" | slurp "$args")"
		[[ $? -ne 0 ]] && exit 1
	fi

	grim -g "$geometry" "$TEMPFILE"

	case "$ANNOTATE" in
	satty)
		satty -f "$TEMPFILE" -o "$TEMPFILE.png" --early-exit --disable-notifications
		;;
	swappy)
		swappy -f "$TEMPFILE" -o "$TEMPFILE.png"
		;;
	esac

	case "${CLIPBOARD[0]}" in
	n)
		save_screenshot
		;;
	o)
		clipboard_screenshot
		;;
	y)
		clipboard_screenshot
		save_screenshot
		;;
	esac
	notify &
	disown
}

while getopts ':f:m:d:c:ona:zp:' arg; do
	case "$arg" in
	m)
		case "${OPTARG,,}" in
		region | window | output | layer | surface)
			MODES+=("${OPTARG,,}")
			;;
		*)
			fail 5 "Invalid mode \"$MODE\""
			;;
		esac
		;;
	c)
		case "$OPTARG" in
		yes | no | only)
			CLIPBOARD="$OPTARG"
			;;
		*)
			fail 3 "$OPTARG Is not a valid clipboard mode"
			;;
		esac
		;;
	a)
		case "${OPTARG,,}" in
		satty)
			ANNOTATE="satty"
			;;
		swappy)
			ANNOTATE="swappy"
			;;
		*)
			if [[ $OPTARG == -* ]] || [[ -z $OPTARG ]]; then
				ANNOTATE="satty"
			else
				fail 4 "Only satty and swappy are supported as annotation apps at the moment"
			fi
			;;
		esac
		;;
	f) FILENAME="$OPTARG" ;;
	o) CLIPBOARD=${CLIPBOARD:-"o"} ;;
	n) CLIPBOARD=${CLIPBOARD:-"n"} ;;
	d) DIRECTORY="${OPTARG%/}" ;;
	z) FREEZE=true ;;
	p)
		FREEZE=false
		PREDEFINED="$OPTARG"
		;;
	\?) fail 1 "Invalid argument -$arg" ;;
	:) fail 2 "No argument provided for -$OPTARG" ;;
	esac
done

grab_init

get_rectangles
echo -n "$RECTANGLES"
capture
